
target 'TuyaSmartHomeKit_Example' do

  pod 'Masonry'
  
  pod 'TYBluetooth', :path => '../'
  pod 'TuyaSmartUtil', :path => '../'
  
  pod 'TuyaSmartHomeKit', :path => '../'
  pod 'TuyaSmartBaseKit', :path => '../'
  pod 'TuyaSmartDeviceKit', :path => '../'
  
  pod 'TuyaSmartBLEKit', :path => '../'
  pod 'TuyaSmartBLEKit', :path => '../'
  pod 'TuyaSmartBLEMeshKit', :path => '../'

  pod 'TuyaSmartMessageKit', :path => '../'
  pod 'TuyaSmartFeedbackKit', :path => '../'
  pod 'TuyaSmartTimerKit', :path => '../'
  pod 'TuyaSmartSceneKit', :path => '../'
  
  pod 'TuyaSmartMQTTChannelKit', :path => '../'
  pod 'TuyaSmartSocketChannelKit', :path => '../'

  
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'BlocksKit'
  pod 'SDWebImage'
  
  pod 'Reachability'

  target 'TuyaSmartHomeKit_Tests' do
    inherit! :search_paths

    
  end
end
