
target 'TuyaSmartHomeKit_Example' do

  pod 'TuyaSmartHomeKit'
  
 pod 'TuyaSmartDemo', :path => '../', :subspecs => [
  'Base',
  'Login',
  'DeviceList',
  'AddDevice',
  'SmartScene',
  'UserInfo']
  
  target 'TuyaSmartHomeKit_Tests' do
    inherit! :search_paths

  end
  
  pod 'MBProgressHUD', '~> 0.9.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
end
