
target 'TuyaSmartHomeKit_Example' do

  pod 'TYBluetooth'
  pod 'TuyaSmartUtil'
  
  pod 'TuyaSmartHomeKit'

  
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'BlocksKit'
  pod 'SDWebImage'

  target 'TuyaSmartHomeKit_Tests' do
    inherit! :search_paths

    
  end
end
